### ISSUE TITLE
Broken callback page after signup attempt

### ISSUE THREAD

**Issue by jofftiquez** [wobsoriano/vue-clerk#1]
Steps to reproduce:

1. Signup using Google
2. Cancel the intent (click the back arrow in the browser)
3. Redirected to 404 page

The page seems to be broken as it loads to the top of the original Signup page.

https://github.com/wobsoriano/vue-clerk/assets/8638243/fef94051-575b-4e4f-9837-dfeb4c7a55f0

**Comment by wobsoriano** [comment]
Updated the examples to use images from Clerk for now :)
