### ISSUE TITLE
Chat application using Vue-Clerk failed in offline environment.

### ISSUE THREAD

**Issue by POABOB** [wobsoriano/vue-clerk#11]
Hey, I am building a chat application in PWA.
I have a situation that user may check the message in offline environment.

When I switch the network off, the clerkjs couldn't initialize properly.
<img width="1348" alt="截圖 2023-12-07 上午11 32 53" src="https://github.com/wobsoriano/vue-clerk/assets/38785340/da79a896-c4ce-45b8-acd9-232baf1e57ed">

I came out a feature that user can set a fallback option, when he/she try to get access to the application with previous clerkjs data.

This feature may may use localStorage or IndexedDB to save the state in browser, and keep watching the network status.
Once the network is online, updating the state immediately.

**Comment by wobsoriano** [comment]
Closing this for now. Looks more of a Clerk issue (which I dont think is an issue)
