### ISSUE TITLE
UserButton bug

### ISSUE THREAD

**Issue by aviorp** [wobsoriano/vue-clerk#128]
when trying to render user button (with nothing special, it worked before update to latest) ui send error alert 
![Screenshot 2024-09-01 at 9 55 23](https://github.com/user-attachments/assets/d7be678e-bd1f-4661-baf8-a11753808271)

**Comment by aviorp** [comment]
![Screenshot 2024-09-01 at 9 56 02](https://github.com/user-attachments/assets/5f25bca2-b8e6-48bc-bc14-9efb3fd73d57)

**Comment by wobsoriano** [comment]
Im not able to replicate this. Would you be able to create a basic repro via stackblitz or something?

**Comment by aviorp** [comment]
i found the issue, you need to specify a sub-component inside <UserButton>, i just dropped there an empty action, and it fixed.. (not the best solution cause i have an error there.
long story short you need to support the component as is without additions (in my opinion)

![Screenshot 2024-09-02 at 10 31 42](https://github.com/user-attachments/assets/6aecee15-e852-48c7-8cdb-c1137de63598)

**Comment by wobsoriano** [comment]
Whats your vue-clerk version?

**Comment by aviorp** [comment]
latest

**Comment by wobsoriano** [comment]
Kk Ill try out later today but would love a stackblitz or repo for a basic repro

**Comment by wobsoriano** [comment]
Still not getting it. Even if you try the starter here - https://github.com/wobsoriano/vue-clerk-quickstart

I suggest you remove `node_modules` and your lockfile then reinstall again.

Feel free to reopen with a reproduction if you want!
