### ISSUE TITLE
How to get access to Clerk instance outside of components?

### ISSUE THREAD

**Issue by Xkonti** [wobsoriano/vue-clerk#136]
Hi! I'm working on an Astro app that utilizes `vue-clerk`. It all works great, but I have a use case where I need access to the Clerk instance in code outside of components. I know that inside the components I can use `useClerk` composable, but how can I get access to it in non-component code?

**Comment by wobsoriano** [comment]
Hello! You can access the `Clerk` instance attached to the `window` object:

```ts
console.log(window.Clerk.loaded)
```

Also, if you don't mind the Vue components and is cool to use Astro components, please see [`@clerk/astro`](https://clerk.com/docs/references/astro/overview). You can use the provided [stores](https://clerk.com/docs/references/astro/overview#client-side-helpers) and create your own composables

**Comment by Xkonti** [comment]
Thanks @wobsoriano ! The `window.Clerk` works great. `@clerk/astro` seems to focus on Astro with server rendering, so I'm gonna stick with `vue-clerk` :)

If somebody else searches for solutions, this is how I ended up using it to connect to SurrealDB database using JWT token from Clerk:

```ts
...
const token = await window.Clerk.session?.getToken();
if (!token) {
  console.error("No token to authenticate with");
  return undefined;
}

await database.connect(SURREALDB_URL, {
  prepare: async (connection) => {
    await connection.use({ namespace: "test", database: "test" });
    await connection.authenticate(token);
  },
});
...
```

**Comment by wobsoriano** [comment]
Glad it worked out for you!

FYI we support [`static` and `hybrid` outputs](https://clerk.com/docs/references/astro/hybrid-rendering) in `@clerk/astro` as well!
