### ISSUE TITLE
on a devServer, guestRedirectUrl switches from https to http

### ISSUE THREAD

**Issue by seaniod** [wobsoriano/vue-clerk#145]
I tried upgrading from 0.4.14, where I had gotten most things working, although with some minor issues remaining.

I tried switching to 0.6.9, using the syntax provided in the current https://github.com/wobsoriano/nuxt-clerk-template/. 

With 0.6.9 on my devServer, all guest login attempts result in the URLs being immediately redirected from https to http, with no messages in either the terminal or the browser console. Since my devServer only accepts https, this results in a "The connection was reset" message, thus preventing me from testing login.

I cannot see any way to configure this. 

I spend several hours unsuccessfully trying to work around this, including:

* trying a /middleware file to redirect back from http to https
* changing or removing the middleware settings in the definePageMeta() statement in the vue page.

FYI here's the nuxt.config.js settings I'm using to enable https with the devServer:

  devtools: {enabled: true},
  devServer: {
    port: 3003,
    host: "0.0.0.0",
    https: {
      key: "./server/certificates/server.key",
      cert: "./server/certificates/server.crt",
    },
  },
  
  FYI here's a video showing the redirect: https://github.com/user-attachments/assets/dff0b772-4aaa-4d1e-b0fc-96f16acd83cf

**Comment by wobsoriano** [comment]
can you update to the latest version and let me know if it works?

**Comment by seaniod** [comment]
G'day,
> can you update to the latest version and let me know if it works?
> 
OK, I spent some time testing ***@***.***  with my application.

I found that the https > http redirect still happens when I do the following:

  https://0.0.0.0:3003 >  http://0.0.0.0:3003/?__clerk_handshake=….

But it doesn’t happen when I use: 

  https://localhost:3003

So, I have a work-around for my case, and hopefully this info will allow your team to reproduce the issue with https://0.0.0.0.

Cheers,
Seán

**Comment by resnikb** [comment]
If it helps, I've been having the same issue, and managed to resolve it by adding this to `nuxt.config.ts`:
```
  app: {
    head: {
      meta: [{ name: 'scheme', content: 'https' }],
    },
  },
```

**Comment by wobsoriano** [comment]
Thanks for the solution @resnikb! Will you be able to try it @seaniod?

**Comment by wobsoriano** [comment]
Feel free to reopen!

**Comment by seaniod** [comment]
I tried with several versions (0.6.9, 0.6.14, and 0.7.2), but unfortunately for me, the above suggestion does not fix the issue. Here's the relevant part of nuxt.config.ts:

export default defineNuxtConfig({
  app: {
    head: { meta: [{ name: "scheme", content: "https" }] },
  },
  devServer: {
    port: 3003,
    host: "0.0.0.0",
    https: {
      key: "./server/certificates/server.key",
      cert: "./server/certificates/server.crt",
    },
  },
});

As previously, whenever I try to use https for the devServer, vue-clerk always causes an immediate redirect from https://localhost:3003 to http://localhost:3003/?__clerk_handshake=….

This fails immediately since http is disabled, resulting in the same attached screenshot I've been seeing for months:

<img width="627" alt="Screenshot 2024-11-05 at 4 51 01 pm" src="https://github.com/user-attachments/assets/e3c202f4-bb2c-4645-93e9-7d980c8f3dce">

Previously, I thought I had this working with 0.6.9, but in fact an old version of my pnpm-lock.yaml file was shadowing these changes. 

I haven't tested extensively, but I believe the last time I had https working for the dev server was vue-clerk 0.4.14.
