### ISSUE TITLE
UserButton.UserProfilePage No Show

### ISSUE THREAD

**Issue by 2322312693** [wobsoriano/vue-clerk#147]
<script setup>
import { UserButton } from 'vue-clerk'

function openChat() {
  alert('init chat')
}
</script>

<template>
  <UserButton>
    <UserButton.MenuItems>
      <UserButton.Action label="Help" open="help">
        <template #labelIcon>
          <Icon />
        </template>
      </UserButton.Action>
    </UserButton.MenuItems>
    <UserButton.UserProfilePage label="Help" url="help">
      <template #labelIcon>
        <Icon />
      </template>
      <div>
        <h1>Help Page</h1>
        <p>This is the custom help page</p>
      </div>
    </UserButton.UserProfilePage>
  </UserButton>
</template>

**Comment by 2322312693** [comment]
`<script setup>
onMounted(() => {
  console.log(UserButton.UserProfilePage)
})
</script>

<template>
  <UserButton>
    <UserButton.MenuItems>
      <UserButton.Action label="Help" open="help">
        <template #labelIcon>
          <Icon />
        </template>
      </UserButton.Action>
    </UserButton.MenuItems>

    <UserButton.UserProfilePage label="Help" labelIcon="help" url="help" class="bg-red-500 w-100 h-100">
      <template #labelIcon>
        <Icon />
      </template>
      <div class="flex flex-col items-center justify-center">
        <h1>Help Page123</h1>
        <p>This is the custom help page</p>
      </div>
    </UserButton.UserProfilePage>
  </UserButton>

  



</template>`


Cannot display in Nuxt3

**Comment by wobsoriano** [comment]
Im not on my PC rn, can you import UserButton from vue-clerk for now so it doesnt try to use the one generated by nuxt?

**Comment by 2322312693** [comment]
I'm glad to hear back from you! I imported the UserButton and created a help button entry. However, when I click the help button, only the overlay appears.

I tried for nearly two hours yesterday.

**Comment by 2322312693** [comment]
vue-clerk@0.6.9

**Comment by wobsoriano** [comment]
> I closed my nuxt project opened vue and tested it but it still doesn't work
> 
> only the mask layer

Do you mean you created a Vue project with Vite and is still getting errors? Can you provide a basic repro via stackblitz or something I can clone?
