### ISSUE TITLE
Reactivity issue?

### ISSUE THREAD

**Issue by Tigran-Harutyunyan** [wobsoriano/vue-clerk#15]
It seems I have reactivity issues. Excuse me if it is not intended by design.

Have a container component with "OrganizationSwitcher" component inside. It switches the organizations perfectly well, but it does not provide any events on changes.

In another component I just want to listen to current organization switch changes. 

In Component 2:

```
const { organization } = useClerk();
```

 this "organization" is not reactive. 

I don`t know how to  listen to changes. Computed props or deep watches are not triggering.
DOM element listening sound stupid. only SetInterval allows to get the up to date info.
```
const clerk = useClerk();

setInterval(() => {
   if (clerk?.organization) {
   ...do whatever with update
  }
}, 1000);

``` 
Maybe I don't understand it well.

Thanks for package and efforts.

**Comment by Tigran-Harutyunyan** [comment]
> Hi, `clerk` from `useClerk` is not reactive, it just returns an instance of the `Clerk` class. If you want a reactive state you can use `derivedState` from `useClerkProvide` for now:
> 
> ```ts
> const { derivedState } = useClerkProvide()
> 
> // derivedState.organization
> ```

Thank you so much for  your hint and implementation details. Really helpful. Great job!  I wish someone  could adapt Convex for Nuxt.

**Comment by wobsoriano** [comment]
> Any plans for "OrganizationList" component? [clerk.com/docs/components/organization/organization-list](https://clerk.com/docs/components/organization/organization-list)

https://github.com/wobsoriano/vue-clerk/pull/16
