### ISSUE TITLE
[ERROR] Could not resolve "@clerk/shared/handleValueOrFn"

### ISSUE THREAD

**Issue by doug-shontz** [wobsoriano/vue-clerk#186]
It would seem that a newer version of the @clerk/backend (specifically updates to @clerk/shared) have broken vue-clerk.  If I install vue-clerk with the necessary @clerk/backend package (just with straight npm i), what I get (as of this writing) is @clerk/backend@1.15.5.  In building Nuxt, I get the error that is the title of this issue.

Looking at the @clerk/backend release schedule, I see they have had a rash of updates in the last day or so.  In fact, I have not experienced this issue until today and I've been working in the affected repo all week.  The workaround for this error is to pin @clerk/backend to 1.15.2.  That version compiles just fine with vue-clerk.

The breaking change seems to be when their monorepo updated to @clerk/shared 2.11.3:  "Refactor imports from @clerk/shared to improve treeshaking support"

**Comment by wobsoriano** [comment]
Thanks for reporting this! Ill check it asap ☺️

**Comment by roder125** [comment]
I have the same problem with nuxt and even going back to older versions of vue-clerk and @clerk/shared, @clerk/backend is not working for me somehow.

**Comment by wobsoriano** [comment]
Hi all, could you please update to the latest version (0.7.2) and confirm if the issue has been resolved?

**Comment by AlekseiAQ** [comment]
Works for me, thank you! @wobsoriano

**Comment by wobsoriano** [comment]
Thanks for confirming! ❤️
