### ISSUE TITLE
let user login as guests

### ISSUE THREAD

**Issue by AbdelilahOu** [wobsoriano/vue-clerk#194]
I am wondering if we can let users log in as guests using clerk and nuxt I have noticed that nuxt clerk module has a guest middleware and is it related to this functionality thanks

**Comment by wobsoriano** [comment]
Hi! Unfortunately, we don't have a way to do guest/anonymous login at the moment. I suggest you upvote the feature and leave a feedback [here](https://feedback.clerk.com/roadmap?id=cc6fe926-0858-43c2-a362-e5f91e5081c3). It's in our backlog.

The `guest` route middleware in `vue-clerk/nuxt` just means to protect public routes from authenticated users. Sorry for the confusion
