### ISSUE TITLE
Clerk provider not found

### ISSUE THREAD

**Issue by jofftiquez** [wobsoriano/vue-clerk#2]
So I was testing vue-clerk in nuxt coz I wanna update the docs to add Nuxt installation guide, but somehow I got this error

> Clerk provider not found

Facts:

- Env is properly loaded
- No visible installation error

Here's my setup:

```js
// nuxt plugin 
// vue-clerk.client.js

import { defineNuxtPlugin, useRuntimeConfig } from '#imports';
import { clerkPlugin } from 'vue-clerk';

export default defineNuxtPlugin({
	setup (nuxtApp) {
		const runtimeConfig = useRuntimeConfig();
		const clerkPublishableKey = runtimeConfig.public.clerkPublishableKey;
		
		console.log(clerkPublishableKey); // has value
		
		nuxtApp.vueApp.use(clerkPlugin, {
	      	publishableKey: clerkPublishableKey,
	    });
	},
});
```

```md
// .env

CLERK_PUBLISHABLE_KEY=pk_test_c3dl...Rlax4 # reducted
```

```js
// nuxt.config.js

...

runtimeConfig: {
 	public: {
    	clerkPublishableKey: process.env.CLERK_PUBLISHABLE_KEY,
  	}, 
},

plugins: [
	'~/plugins/vue-clerk.client.js',
]

...

```

Screenshot

![image](https://github.com/wobsoriano/vue-clerk/assets/8638243/49869b34-118d-4c24-9891-5ff0df53ed64)

**Comment by wobsoriano** [comment]
Yo! You also need to add the clerk-js module to `build.transpile`. I have a Nuxt template actually if you want to check out - https://github.com/wobsoriano/nuxt-clerk-template

**Comment by jofftiquez** [comment]
> Yo! You also need to add the clerk-js module to `build.transpile`. I have a Nuxt template actually if you want to check out - [wobsoriano/nuxt-clerk-template](https://github.com/wobsoriano/nuxt-clerk-template)

Nice! Thanks @wobsoriano got it. Will review and update this issue, thanks!

**Comment by Atinux** [comment]
When the vue-clerk/nuxt module? 😜

**Comment by wobsoriano** [comment]
@Atinux soon! :)

**Comment by wobsoriano** [comment]
Let me know if are still experiencing this issue! There's a Nuxt template for now - https://github.com/wobsoriano/nuxt-clerk-template
