### ISSUE TITLE
I think OrganizationsList is not imported. https://github.com/wobsoriano/vue-clerk/blob/main/src/index.ts

### ISSUE THREAD

**Issue by Tigran-Harutyunyan** [wobsoriano/vue-clerk#20]
I think OrganizationsList is not imported. https://github.com/wobsoriano/vue-clerk/blob/main/src/index.ts
updated the package but import is not available. Thank you.

_Originally posted by @Tigran-Harutyunyan in https://github.com/wobsoriano/vue-clerk/issues/16#issuecomment-1923604229_
 Hi Robert. Please don`t forget the import issue of OrganizationList. It is unavailable.

**Comment by wobsoriano** [comment]
FYI there's a basic implementation of `useOrganization`

```ts
const { isLoaded, organization } = useOrganization()
```

**Comment by Tigran-Harutyunyan** [comment]
> FYI there's a basic implementation of `useOrganization`
> 
> ```ts
> const { isLoaded, organization } = useOrganization()
> ```

Thank you Robert. Just pulled the version ^0.1.6. Having issues. error 500. "The requested module '/_nuxt/node_modules/vue-clerk/dist/index.mjs?v=67b9e195' does not provide an export named 'OrganizationList'"
