### ISSUE TITLE
During clerk plugin initialization when I am passing my publishable key I am getting following issue

### ISSUE THREAD

**Issue by RafaelHovhannisyan** [wobsoriano/vue-clerk#203]
import App from '@/App.vue'
import router from '@/router'
import { createApp } from 'vue'
import { clerkPlugin } from 'vue-clerk'
import { CLERK_PUBLISHABLE_KEY } from '@/common/consts/env'

console.log(CLERK_PUBLISHABLE_KEY)

if (!CLERK_PUBLISHABLE_KEY) {
  throw new Error('Missing Publishable Key')
}

const app = createApp(App)

app.use(router)

app.use(clerkPlugin, {
  publishableKey: CLERK_PUBLISHABLE_KEY,
})

app.mount('#app')

Uncaught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded

**Comment by wobsoriano** [comment]
Hello! Would you be able to provide a basic repro?

**Comment by RafaelHovhannisyan** [comment]
Unfortunately, I can't. I am just in the phase of setting up my project. I took the publishable key from the clerk dashboard, added it to my environment, and used it in the main.js/ts file, but I am getting this issue.

Here are packages in use
"@clerk/clerk-js": "^5.22.3"
"@clerk/shared": "^2.14.0"
"vue-clerk": "^0.8.5"

**Comment by wobsoriano** [comment]
Any reason you have `@clerk/clerk-js` and `@clerk/shared` installed?

Can you run this for me?

```bash
npx envinfo --system --npmPackages vue,vue-clerk,vite --binaries --browsers
```

**Comment by wobsoriano** [comment]
Feel free to reopen!
