### ISSUE TITLE
RedirectToSignIn Component Repeats OAuth Authorization Request

### ISSUE THREAD

**Issue by ztroop** [wobsoriano/vue-clerk#215]
I'm following the documentation and I have the following on my main page:

```
  <SignedOut>
    <RedirectToSignIn signInForceRedirectUrl="/" />
  </SignedOut>
```

Which works wonderfully, but it _always_ asks for OAuth authorization each time I sign in. It's not exactly clear to me why this is the case. Any help is appreciated! Kind Regards

**Comment by ztroop** [comment]
I don't think this is an issue with `vue-clerk` itself. It appears to be an upstream issue in `clerk`. My suspicion is a CSP issue during local development:

> Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at https://clerk.accounts.dev/npm/@clerk/clerk-js@5/dist/clerk.browser.js from being executed because it violates the following directive: “default-src 'self' https://ready-skink-36.accounts.dev/ https://ready-skink-36.clerk.accounts.dev/ https://cdn.jsdelivr.net/ https://js.sentry-cdn.com/ https://browser.sentry-cdn.com/ https://*.ingest.sentry.io https://challenges.cloudflare.com/ https://scdn.clerk.com/ https://segapi.clerk.com/”

Closing.

**Comment by wobsoriano** [comment]
Hi! Just wanted to let you know that we now have an official [Nuxt SDK](https://clerk.com/docs/references/nuxt/overview) at Clerk. The docs are live and it's ready to use, though we'll do the public announcement in January. Feel free to check it out!
