### ISSUE TITLE
Nuxt fails to start on Windows when using vue-clerk/server to protect an api

### ISSUE THREAD

**Issue by franciscohermida** [wobsoriano/vue-clerk#216]
```ERROR  [worker reload] [worker init] D:/Repos/vue-clerk-playground-3/.nuxt/dev/index.mjs failed```

Repro: https://github.com/wobsoriano/vue-clerk/tree/main/apps/playground

**Comment by wobsoriano** [comment]
Hi! Did you try to run the playground or?

**Comment by franciscohermida** [comment]
I cloned it and tried to run on my computer, when I comment out clerkClient and getAuth usage it works.

I did it on my own nuxt app when following the nuxt guide of vue-clerk, when I tried to use clerkClient and getAuth to protect the api I got the same error, then I tried cloning the playground to see if it was happening there as well which it did. 

- I cloned the repo
- copied the playground folder by itself
- replaced the "workspace:*" package entry with the npm one
- pnpm install (didn't work)
- nuxi upgrade (didn't work)

here a repro on stackblitz:
https://stackblitz.com/edit/nuxt-starter-oxhvkv?file=server%2Fapi%2Fprotected.ts

**Comment by wobsoriano** [comment]
Try this

1. `pnpm install`
2. `pnpm build-packages`
3. `pnpm --filter playground dev`

**Comment by franciscohermida** [comment]
I cannot repoen this issue, I will create a new issue.

**Comment by wobsoriano** [comment]
Hmmm I think you missed [this part](https://www.vue-clerk.com/guides/nuxt#_2-install-module)?

**Comment by franciscohermida** [comment]
You are correct, I missed it in the stackblitz reproduction. I will try to reproduce the issue again being more careful, trying to replicate it with the playground and my own app, sorry for the inconvenience. I will update here once I finish.

**Comment by franciscohermida** [comment]
Ok I think I know what is causing the issue and why it can be very confusing to reproduce.

It seems to only happen on windows. If I clone this new stackblitz project (just added ```modules: ['vue-clerk/nuxt']```) on windows it doesn't work, if I do it on a mac it works.
https://stackblitz.com/edit/nuxt-starter-wfhsx4

**Comment by franciscohermida** [comment]
The issue also happens on a fresh windows VM, with just pnpm and node installed

**Comment by wobsoriano** [comment]
I tried it on my windows PC, using this [template](https://github.com/wobsoriano/nuxt-clerk-template). It's running smooth 🤔

**Comment by franciscohermida** [comment]
> I tried it on my windows PC, using this [template](https://github.com/wobsoriano/nuxt-clerk-template). It's running smooth 🤔

It runs smooth because it doesn't have an api protected by vue-clerk/server as I mentioned.

**Comment by franciscohermida** [comment]
I can confirm the issue is now resolved on my end. Thank you for fixing this!
