### ISSUE TITLE
NUXT_SECRET_KEY must be exposed?

### ISSUE THREAD

**Issue by landrybielefeldipelint** [wobsoriano/vue-clerk#225]
It may be a quirk of the documentation but the Nuxt documentation on vue-clerk details out that both the publishable and secret key must be placed in the .env.local.

This would be fine in development but what about production? vue-clerk relies on @clerk/backend which needs the secret key.

**Is there no way to deploy this without exposing the secret key?**

**Comment by landrybielefeldipelint** [comment]
**You cannot remove @clerk/backend for the dependency reason**

[12:17:22 PM]  WARN  "@clerk/backend/internal" is imported by "node_modules/vue-clerk/dist/nuxt/runtime/server/clerkMiddleware.js", but could not be resolved – treating it as an external dependency.


[12:17:22 PM]  WARN  "@clerk/backend" is imported by "node_modules/vue-clerk/dist/nuxt/runtime/server/clerkClient.js", but could not be resolved – treating it as an external dependency

**And you cannot use it for the secret key reason:**

ℹ Vite server warmed up in 1029ms                                                    12:18:32 PM

 ERROR  [nuxt] [request error] [unhandled] [500] Missing Clerk Secret Key. Go to https://dashboard.clerk.com and get your key for your instance.



 ERROR  [nuxt] [request error] [unhandled] [500] Missing Clerk Secret Key. Go to https://dashboard.clerk.com and get your key for your instance.

**Comment by landrybielefeldipelint** [comment]
It works if I add the secret key but this of course will expose it on upload

**Comment by wobsoriano** [comment]
Hi, did you follow the steps [here](https://www.vue-clerk.com/guides/nuxt) and installed `@clerk/backend`? You need both of the ff. keys:

```ts
NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY=your_publishable_key
NUXT_CLERK_SECRET_KEY=your_secret_key
```

**Comment by landrybielefeldipelint** [comment]
Yes I did!

The issue is not getting it to work but the reality of if I now where to publish the site, the secret key will be exposed along with the publishable key (it is ok the publishable key is exposed)

**Am I under the wrong assumption about the secret key? Can it be exposed with no security risk?**

**Comment by wobsoriano** [comment]
No, private keys are only available server side. It will no be exposed. See [this](https://nuxt.com/docs/guide/going-further/runtime-config#exposing).

**Comment by landrybielefeldipelint** [comment]
Gotcha! Ok. 
I believe I am understanding you and I didn't realize nuxt had that functionality.

Is there anything extra I need to do in the nuxt.config.ts or will the NUXT_CLERK_SECRET_KEY be enough in the .env?

**Comment by wobsoriano** [comment]
> Gotcha! Ok. I believe I am understanding you and I didn't realize nuxt had that functionality.
> 
> Is there anything extra I need to do in the nuxt.config.ts or will the NUXT_CLERK_SECRET_KEY be enough in the .env in that nuxt will handle the rest of the server-side security?

All good! No extra config needed 😄 The module will read your env variables automatically.

You can see full list of env vars [here](https://clerk.com/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects). Just replace `NEXT_` there with `NUXT_`

**Comment by landrybielefeldipelint** [comment]
Thank you so much! That cleared things up well!

Thank you so much for the support and help! Grateful for it!

**Comment by landrybielefeldipelint** [comment]
All good here!

**Comment by wobsoriano** [comment]
You're welcome!
