### ISSUE TITLE
Nitro support

### ISSUE THREAD

**Issue by MickL** [wobsoriano/vue-clerk#230]
It would be nice if the module can be used for pure Nitro projects. As Nuxt is using Nitro (which in turn is using H3) it should be pretty much the same code.

1. I think Nitro modules [dont work the way they do in Nuxt](https://github.com/nitrojs/nitro/pull/2508) but Nitro layers and Nitro plugins can be used
2. Maybe for the integrated middlewares, just an example code could be provided, e.g. "Create middleware/auth.ts"
3. Instead of `navigateTo()` i would always `throw createError({ status: 401 })`
4. env variables should be prefixed with `NITRO_` and there is no public:

```
NITRO_CLERK_SECRET_KEY=
NITRO_CLERK_PUBLISHABLE_KEY=
```

**Comment by wobsoriano** [comment]
If I understand correctly, you just want to use the server middleware and not the Vue components?

**Comment by MickL** [comment]
Yes exactly:

* Use clerk client preconfigured with NITRO_ variables
* Use `getAuth()`
* Protect routes by a middleware (Having an example might be enough)

I am hoping that Nitro gets more support because mostly everything exists for Nuxt but not for Nitro.

**Comment by wobsoriano** [comment]
Hmm for now maybe you can use [h3-clerk](https://github.com/wobsoriano/h3-clerk) as an inspiration to create your own Clerk middleware

**Comment by wobsoriano** [comment]
Closing this for now. No plans to add separate Nitro support for vue-clerk 🫡 sorry

**Comment by MickL** [comment]
If you leave it open I might add Nitro support, but I am still considering to just implement auth/sessions myself or if I want to use Clerk
