### ISSUE TITLE
ClerkProvider for localization

### ISSUE THREAD

**Issue by hloehrmann** [wobsoriano/vue-clerk#25]
Would it be possible to have the ClerkProvider component so the experimental localization prop can be used? 

Or is there any other way to set it?

See here for reference: https://clerk.com/docs/components/customization/localization

Thanks and all the best!

**Comment by wobsoriano** [comment]
Hey!

You can pass it in the plugin options:

```ts
import { clerkPlugin } from 'vue-clerk/plugin'
import { frFR } from '@clerk/localizations'

const app = createApp(App)

app.use(clerkPlugin, {
  publishableKey: import.meta.env.VITE_CLERK_PUBLISHABLE_KEY,
  appearance: {},
  localization: frFR
})
```

I haven't tested this but let me know if it works for you!

**Comment by hloehrmann** [comment]
Yes, it works! Thanks for the quick response - I think this might actually be worth noting in the documentation...

Correct syntax is this one by the way:

```
app = createApp(App)
    .use(clerkPlugin, {
      publishableKey: import.meta.env.VUE_APP_CLERK_PUBLISHABLE_KEY,
      options: {
        localization: deDE,
      },
    })
```

With `options`  beeing the `ClerkOptions `interface.

**Comment by wobsoriano** [comment]
Heads up - Im opening a breaking change PR moving the options object at the root of the plugin options

https://github.com/wobsoriano/vue-clerk/pull/26
