### ISSUE TITLE
Upgrading from 0.1.7 to 0.3.7 breaks local development

### ISSUE THREAD

**Issue by alan-funded** [wobsoriano/vue-clerk#35]
Upgrading from 0.1.7 to 0.3.7 breaks local development: The clerk client on locahost keeps issuing gets and posts to clerk servers at a high pace until eventually we get a 429 back. 

`Failed to load resource: the server responded with a status of 429 ()`

**Comment by wobsoriano** [comment]
Do you get this error with h3-clerk?

**Comment by wobsoriano** [comment]
You might want to check the Nuxt + Clerk template - https://github.com/wobsoriano/nuxt-clerk-template

**Comment by alan-funded** [comment]
Yeah, I did, but that had some middleware issues, not sure if they are
resolved: https://github.com/wobsoriano/nuxt-clerk-template/issues/6

At this point I'd have to port my Vue FE + Next BE to Nuxt. Maybe later.

**Comment by wobsoriano** [comment]
Please check the nuxt + clerk template again and make sure to update to latest h3-clerk version as well!

**Comment by wobsoriano** [comment]
Feel free to reopen
