### ISSUE TITLE
Redirect not working with SignedIn and SignedOut

### ISSUE THREAD

**Issue by rgdcastro** [wobsoriano/vue-clerk#36]
**Description:**
I've encountered an issue where the redirect functionality doesn't seem to work when using the SignedIn and SignedOut components. Instead it just displays blank white page.

**Steps to Reproduce:**

- Implement SignedIn and SignedOut components in the application.
- Attempt to trigger a redirect.

**Observations:**
The redirect does not occur as expected.

Additional Information:
I have tried going through releases and it broke after version 0.3.0

**Comment by wobsoriano** [comment]
That's how it behaves 👀 `SignedIn` component will only render its children if authenticated.

You'd want to use it with the [`RedirectToSignIn`](https://vue-clerk.vercel.app/control/redirect-to-signin#props) component:

```html
<SignedIn>
  <h1>Index route</h1>
  <p>You are signed in!</p>
  <UserButton />
</SignedIn>
<SignedOut>
  <RedirectToSignIn  />
</SignedOut>
```

**Comment by rgdcastro** [comment]
Sorry if my initial message was not clear. Yes, I am already using the RedirectToSignIn component. I'll try to send a sample repo later.

![image](https://github.com/wobsoriano/vue-clerk/assets/36554808/e78f04b6-ae77-49b3-9203-8e6245a1ef31)

Thanks!

**Comment by wobsoriano** [comment]
Thank you. Appreciate the report!

**Comment by wobsoriano** [comment]
Hey, I tried a fresh Nuxt project and tried to mimic your example. Redirect works like expected. Can you try the latest vue-clerk version?

**Comment by wobsoriano** [comment]
Hey, I'm closing this for now. Please use the latest version and check if the error still persists. If it does, feel free to reopen it!
