### ISSUE TITLE
i18n implementation?

### ISSUE THREAD

**Issue by aviorp** [wobsoriano/vue-clerk#38]

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-clerk/issues/25#issuecomment-1950410106

**Comment by aviorp** [comment]
```
import { clerkPlugin } from 'vue-clerk/plugin';
import { heIL } from '@clerk/localizations';
export default defineNuxtPlugin(({ vueApp }) => {
  vueApp.use(clerkPlugin, {
    publishableKey: useRuntimeConfig().public.clerkPublishableKey,
    localization: heIL,
  });
});
```

idk what im missing but im sure its not working that way, any thoughts ?

**Comment by wobsoriano** [comment]
What's not working @aviorp? Can you update to latest version and try again?

I just tried it in the [playground](https://github.com/wobsoriano/vue-clerk/blob/300d44352f83bee0f588f9dd75fd1e36aeb0946e/playground/plugins/clerk.client.ts#L8) and it works as expected:

![Screenshot 2024-05-28 at 9 11 08 AM](https://github.com/wobsoriano/vue-clerk/assets/13049130/eacc82d6-20eb-4630-a5f4-6d10c0390e7a)

**Comment by aviorp** [comment]
well it works ! forgot to refresh my lock file. thanks man !

**Comment by aviorp** [comment]
btw how can i toggle the mode by user choice ?

**Comment by wobsoriano** [comment]
@aviorp It's not documented but here's how you would do it:

```ts
import { frFR } from '@clerk/localizations'

const clerk = useClerk()

clerk.__unstable__updateProps({ options: { ...currentOptions, locale: frFR } })
```
