### ISSUE TITLE
Nuxt.js hash routing error

### ISSUE THREAD

**Issue by nlaurie** [wobsoriano/vue-clerk#43]
Have you ever seen this issue 

Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#/factor-one' is not a valid selector.

See like there is an issue with the hash routing an nuxt.  

However it still logs in , just posts and error in the console and gets reported via sentry.

**Comment by wobsoriano** [comment]
Related https://github.com/nuxt/nuxt/issues/15381
