### ISSUE TITLE
Unable to get package working with Astro+Vue

### ISSUE THREAD

**Issue by serdar** [wobsoriano/vue-clerk#44]
Hello,
I've been trying to integrate vue-clerk with my Astro project but received the following error below. The Astro project has SSR enabled via the Cloudflare adapter and is running the Vue integration as well.

`[astro-island] Error hydrating /src/pages/admin/Signin.vue TypeError: mod.default is not a function`

Repo:
https://github.com/serdar/astro-vue-clerk-demo

Stackblitz:
https://stackblitz.com/~/github.com/serdar/astro-vue-clerk-demo

Thanks

**Comment by wobsoriano** [comment]
Here's a PR fixing the issues - https://github.com/serdar/astro-vue-clerk-demo/pull/1

1. You don't have to manually mount the vue app instance again
2. Public env vars should start with `PUBLIC_`

There is also a community maintained Astro Clerk integration - https://clerk.com/changelog/2024-03-28
