### ISSUE TITLE
Documentation pages missing or partly hidden

### ISSUE THREAD

**Issue by seaniod** [wobsoriano/vue-clerk#46]
The vue-clerk documentation pages act a bit weird:

1. If I start on the [home page](https://vue-clerk.vercel.app) then click on [What is Vue Clerk?](https://vue-clerk.vercel.app/what-is-vue-clerk), both pages display nicely.

2. If I then reload [What is Vue Clerk?](https://vue-clerk.vercel.app/what-is-vue-clerk), two things happen: (1) the main content for this page disappears and (2) the left 25% of the page is hidden behind the navigation component. See screenshot 1.

3. When I next use the navigation mention to navigation go to any other documentation page, the main content for each page does appear correctly, but the left 25% of each page is still hidden behind the navigation component. See screenshot 2.

4. If I then use the navigation menu to go back to the [What is Vue Clerk?](https://vue-clerk.vercel.app/what-is-vue-clerk) page, the main content reappears, but the 25% issue remains.

 I see exactly the same issues using Firefox, Chrome, or Safari. I'm working on a MacBook Pro running Venutra 13.6.7.

**Screenshot 1**
<img width="1552" alt="Screenshot 2024-06-23 at 3 04 30 pm" src="https://github.com/wobsoriano/vue-clerk/assets/2742708/3d269ccf-efde-4d94-b31d-a261756e092c">

**Screenshot 2**
<img width="1552" alt="Screenshot 2024-06-23 at 3 04 21 pm" src="https://github.com/wobsoriano/vue-clerk/assets/2742708/dcf420f8-fcb5-4191-9304-b93f84852fd6">

**Comment by wobsoriano** [comment]
Thanks for reporting! I also experience this issue and thought it was a caching issue or something on my end. I'll check this asap!

**Comment by wobsoriano** [comment]
Fixed using https://vercel.com/docs/projects/project-configuration#cleanurls
