### ISSUE TITLE
Accessing ClerkProvider

### ISSUE THREAD

**Issue by seaniod** [wobsoriano/vue-clerk#63]
A feature request would be to enable access to ClerkProvider.

It seems using ClerkProvider is the only way to set themes or to customize styling for clerk elements.

**Comment by wobsoriano** [comment]
Hi! Are you trying to update the props passed in the plugin? For now you can do something like

```ts
const clerk = useClerk()
clerk.__unstable__updateProps({ options: { localization: frFR } })
```

or if outside a setup component

```ts
window.Clerk.__unstable__updateProps({ options: { localization: frFR } })
```
