### ISSUE TITLE
useOrganizationList()

### ISSUE THREAD

**Issue by CptJJ** [wobsoriano/vue-clerk#64]
It doesnt seem like there is currently a way to switch orgs, as I would expect some kind of useOrganizationList() to match https://clerk.com/docs/references/javascript/organization/members

maybe there is a word around you can advise on?

**Comment by wobsoriano** [comment]
Hey yeah unfortunately that composable is not yet implemented, but you can [build your custom flow](https://clerk.com/docs/organizations/custom-organization-switcher) with `useClerk` and `useUser` composables for now:

```ts
const clerk = useClerk()
const { user } = useUser()

// This is paginated
const memberships = await user.value.getOrganizationMemberships()

await clerk.setActive({ organization: memberships.data[0].organization.id })
```

**Comment by CptJJ** [comment]
Oh perfect thank you!

**Comment by wobsoriano** [comment]
Feel free to reopen!
